class NetSuiteResponseError(Exception): ...


class RateLimitExceededError(Exception): ...


class NetSuiteNotInitializedError(Exception): ...


class InvalidNetSuiteResponseError(Exception): ...


class MismatchConditionsError(Exception): ...


class ConfigurationError(Exception): ...


class DoesNotExistError(Exception): ...


class NetSuiteDataChangedError(Exception): ...
